name: rest_api_example
description: "A flutter example using retrofit and dio"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.7.0
  retrofit: ^4.4.1
  json_annotation: ^4.9.0
  provider: ^6.1.2
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.12
  retrofit_generator: ^8.1.0
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
